### ISSUE TITLE
iPad App

### ISSUE THREAD

**Issue by kraetos10** [Bunn/PiStatsMobile#2]
Would be great to have an iPad app - happy to help dev it if required :-) Or I could fork your repo and give it a go...

**Comment by Bunn** [comment]
@chriswunsch00 yep, I do want to create an iPad version, I just want to iron out some things first and then give it a go.
Thanks for the suggestion, if I need help I'll let you know, thanks for offering, I really appreciate it 👍

**Comment by kraetos10** [comment]
@Bunn no worries man - love the app btw, just downloaded the Mac version off store!

**Comment by Bunn** [comment]
Version 2.0.0 has the initial iPad OS support. More to come :)

**Comment by kraetos10** [comment]
> Version 2.0.0 has the initial iPad OS support. More to come :)

Nice work - anything you want me to beta test ?

**Comment by Bunn** [comment]
no, not yet, but thank you though :)
