### ISSUE TITLE
Widget should display a “X” when offline (ie: under 4G)

### ISSUE THREAD

**Issue by giuliomagnifico** [Bunn/PiStatsMobile#3]
Hi, I think the widget should display the same “X” as the app when the Pi-Hole is offline but doesn’t display nothing when he fails to refresh stats. Here’s a link to the video of the behavior: https://imgur.com/a/awsp2WD

Thanks

**Comment by Bunn** [comment]
This seems to be happening because the timeout interval is too high, I changed from the default which I think it's 60 to 10, which then makes the widget update in case of a timeout much faster.

Here's a video illustrating how it's working now: https://i.imgur.com/fKyWghV.mp4

**Comment by Bunn** [comment]
Fixed on 1.2.1

**Comment by giuliomagnifico** [comment]
Yes thanks! Now it works as expected!

Giulio Magnifico
www.giuliomagnifico.it
